# Generated by Django 5.1.6 on 2025-07-22 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitalizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Capitalizacion',
                'verbose_name_plural': 'Capitalizaciones',
                'db_table': 'capitalizaciones',
            },
        ),
        migrations.CreateModel(
            name='DestinosCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_codigo', models.CharField(max_length=10, unique=True)),
                ('dest_descripcion', models.CharField(max_length=255)),
                ('dest_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'DestinoCredito',
                'verbose_name_plural': 'DestinosCreditos',
                'db_table': 'destinosCredito',
            },
        ),
        migrations.CreateModel(
            name='FormasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpago_codigo', models.CharField(max_length=10, unique=True)),
                ('fpago_descripcion', models.CharField(max_length=255)),
                ('fpago_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FormaPago',
                'verbose_name_plural': 'FormasPagos',
                'db_table': 'formaPagos',
            },
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parm_abreviatura', models.CharField(max_length=20, unique=True)),
                ('parm_descripcion', models.CharField(max_length=255)),
                ('parm_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parm_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parametro',
                'verbose_name_plural': 'Parametros',
                'db_table': 'parametros',
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_año', models.PositiveIntegerField(default=2000)),
                ('periodo_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PeriodoContable',
                'verbose_name_plural': 'PeriodosContables',
                'db_table': 'periodosContables',
            },
        ),
        migrations.CreateModel(
            name='PlazoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_descripcion', models.CharField(max_length=255)),
                ('pf_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf_plazo', models.IntegerField()),
                ('pf_tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pf_fecha_vencimiento', models.DateField()),
                ('pf_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PLazoFijo',
                'verbose_name_plural': 'PlazosFijos',
                'db_table': 'plazofijo',
            },
        ),
        migrations.CreateModel(
            name='Representantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presidente', models.CharField(max_length=150)),
                ('administrador', models.CharField(max_length=150)),
                ('secretario', models.CharField(max_length=150)),
                ('tesorero_aso', models.CharField(max_length=150)),
                ('tesorero', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'db_table': 'representantes',
            },
        ),
        migrations.CreateModel(
            name='TiposAFuturos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tafuturo_abreviatura', models.CharField(max_length=15, unique=True)),
                ('tafuturo_tipo', models.CharField(max_length=100)),
                ('tafuturo_v_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tafuturo_v_periodico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tafuturo_penalizacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tafuturo_plazo', models.IntegerField()),
                ('tafuturo_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TipoAFuturo',
                'verbose_name_plural': 'TiposAFuturos',
                'db_table': 'tiposAFuturos',
            },
        ),
        migrations.CreateModel(
            name='TiposCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcredito_abreviatura', models.CharField(max_length=20, unique=True)),
                ('tcredito_tipo', models.CharField(max_length=100)),
                ('tcredito_monto_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcredito_tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tcredito_porcentaje_mora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tcredito_num_cuotas', models.IntegerField()),
                ('tcredito_aporte_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcredito_porcentaje_encaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tcredito_gracia', models.IntegerField()),
                ('tcredito_estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TipoCredito',
                'verbose_name_plural': 'TiposCreditos',
                'db_table': 'tiposCreditos',
            },
        ),
        migrations.CreateModel(
            name='InteresAFuturo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iafuturo_rendimiento', models.CharField(max_length=100)),
                ('iafuturo_v_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iafuturo_v_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iafuturo_estado', models.BooleanField(default=True)),
                ('iafuturo_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.tiposafuturos')),
            ],
            options={
                'verbose_name': 'InteresAFuturo',
                'verbose_name_plural': 'InteresAFuturos',
                'db_table': 'interesAFuturos',
            },
        ),
        migrations.CreateModel(
            name='TiposAhorros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahorro_abreviatura', models.CharField(max_length=20, unique=True)),
                ('tahorro_tipo', models.CharField(max_length=255)),
                ('tahorro_dia_aporte', models.IntegerField()),
                ('tahorro_meses_minimo', models.IntegerField()),
                ('tahorro_porcent_aporte', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tahorro_estado', models.BooleanField(default=True)),
                ('tahorro_capitalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.capitalizaciones')),
            ],
            options={
                'verbose_name': 'TipoAhorro',
                'verbose_name_plural': 'TiposAhorros',
                'db_table': 'tiposAhorros',
            },
        ),
        migrations.CreateModel(
            name='InteresAhorros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iahorro_rendimiento', models.CharField(max_length=100)),
                ('iahorro_v_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iahorro_v_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iahorro_estado', models.BooleanField(default=True)),
                ('iahorro_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.tiposahorros')),
            ],
            options={
                'verbose_name': 'InteresAhorro',
                'verbose_name_plural': 'InteresAhorros',
                'db_table': 'interesAhorros',
            },
        ),
    ]
