# Generated by Django 5.1.6 on 2025-07-22 23:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablasAmortizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'TablaAmortizacion',
                'verbose_name_plural': 'TablasAmortizaciones',
                'db_table': 'tablasAmortizaciones',
            },
        ),
        migrations.CreateModel(
            name='SolicitudesCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_nro_solicitud', models.CharField(max_length=10, unique=True)),
                ('sol_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sol_cuotas', models.IntegerField()),
                ('sol_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sol_comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sol_valor_encaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sol_monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sol_valor_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sol_garante', models.BooleanField(default=False)),
                ('sol_nombres_garante', models.CharField(blank=True, max_length=200, null=True)),
                ('sol_nro_garante', models.CharField(blank=True, max_length=10, null=True)),
                ('sol_s_creditos', models.CharField(blank=True, max_length=100, null=True)),
                ('sol_fecha_solicitud', models.DateField(default=django.utils.timezone.now)),
                ('sol_fecha_vencimiento', models.DateField()),
                ('sol_forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.formaspago')),
                ('sol_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
                ('sol_tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.tiposcredito')),
                ('sol_tipo_tabla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operativo.tablasamortizacion')),
            ],
            options={
                'verbose_name': 'SolicitudCredito',
                'verbose_name_plural': 'SolicitudesCreditos',
                'db_table': 'solicitudesCreditos',
            },
        ),
    ]
