# Generated by Django 5.1.6 on 2025-07-24 14:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0001_initial'),
        ('usuarios', '0002_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasAhorros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ah_fecha_apertura', models.DateField(default=django.utils.timezone.now)),
                ('ah_saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ah_no_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilusuario')),
            ],
            options={
                'verbose_name': 'CuentaAhorro',
                'verbose_name_plural': 'CuentasAhorros',
                'db_table': 'cuentasAhorros',
            },
        ),
    ]
