# Generated by Django 5.1.6 on 2025-07-25 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0002_cuentasahorros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentasahorros',
            name='ah_fecha_apertura',
        ),
    ]
