# Generated by Django 5.1.6 on 2025-08-04 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0003_remove_cuentasahorros_ah_fecha_apertura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTransacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_tipo', models.CharField(max_length=10)),
                ('trans_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trans_saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trans_fecha', models.DateTimeField()),
                ('trans_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transacciones',
                'ordering': ['-trans_fecha'],
            },
        ),
    ]
