# Generated by Django 5.1.6 on 2025-08-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0004_historialtransacciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudescredito',
            name='sol_nombres_garante',
        ),
    ]
