# Generated by Django 5.1.6 on 2025-08-07 02:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0005_remove_solicitudescredito_sol_nombres_garante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditosAprobados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito_fecha_aprobacion', models.DateField(default=django.utils.timezone.now)),
                ('credito_estado', models.BooleanField(default=True)),
                ('credito_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operativo.solicitudescredito')),
                ('credito_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CreditoAprobado',
                'verbose_name_plural': 'CreditosAprobados',
                'db_table': 'creditosAprobados',
            },
        ),
        migrations.CreateModel(
            name='PagosCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_fecha', models.DateField(default=django.utils.timezone.now)),
                ('pago_monto_capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_monto_interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_monto_comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_monto_seguro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_numero_cuota', models.IntegerField()),
                ('pago_fecha_vencimiento', models.DateField()),
                ('pago_estado', models.BooleanField(default=True)),
                ('pago_saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pago_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operativo.creditosaprobados')),
                ('pago_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PagoCredito',
                'verbose_name_plural': 'PagosCreditos',
                'db_table': 'pagosCreditos',
            },
        ),
    ]
