# Generated by Django 5.1.6 on 2025-08-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0007_alter_historialtransacciones_trans_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudescredito',
            name='sol_disponible',
        ),
    ]
