# Generated by Django 5.1.6 on 2025-08-20 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0008_remove_solicitudescredito_sol_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadosSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'EstadoSolicitud',
                'verbose_name_plural': 'EstadosSolicitudes',
                'db_table': 'estadosSolicitudes',
            },
        ),
        migrations.RemoveField(
            model_name='solicitudescredito',
            name='sol_fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='solicitudescredito',
            name='sol_s_creditos',
        ),
        migrations.AddField(
            model_name='solicitudescredito',
            name='sol_saldo_credito',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudescredito',
            name='sol_nro_garante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudescredito',
            name='sol_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operativo.estadossolicitud'),
            preserve_default=False,
        ),
    ]
