# Generated by Django 5.1.6 on 2025-08-20 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0009_estadossolicitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudescredito',
            name='sol_valor_cuota',
        ),
        migrations.AddField(
            model_name='solicitudescredito',
            name='sol_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudescredito',
            name='sol_tipo_tabla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operativo.tablasamortizacion'),
        ),
    ]
