# Generated by Django 5.1.6 on 2025-08-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0010_remove_solicitudescredito_sol_valor_cuota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudescredito',
            name='sol_saldo_credito',
        ),
        migrations.AddField(
            model_name='creditosaprobados',
            name='credito_saldo_credito',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
            preserve_default=False,
        ),
    ]
