# Generated by Django 5.1.6 on 2025-08-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0011_remove_solicitudescredito_sol_saldo_credito_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditosaprobados',
            old_name='credito_saldo_credito',
            new_name='credito_saldo',
        ),
    ]
