# Generated by Django 5.1.6 on 2025-08-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0012_rename_credito_saldo_credito_creditosaprobados_credito_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudescredito',
            name='sol_observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
