# Generated by Django 5.1.6 on 2025-08-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0013_solicitudescredito_sol_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudescredito',
            name='sol_observacion',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
    ]
