# Generated by Django 5.1.6 on 2025-05-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simu_nombre', models.CharField(max_length=100)),
                ('simu_tipo_credito', models.CharField(choices=[('educacion', 'Educación'), ('vacaciones', 'Vacaciones'), ('construccion', 'Construcción'), ('emergencia', 'Emergencia')], max_length=20)),
                ('simu_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('simu_meses', models.IntegerField()),
                ('simu_interes_anual', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Simulacion',
                'verbose_name_plural': 'Simulaciones',
                'db_table': 'simulaciones',
            },
        ),
    ]
