# Generated by Django 5.1.6 on 2025-07-22 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'EstadoCivil',
                'verbose_name_plural': 'EstadosCiviles',
                'db_table': 'estadoCivil',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('fecha_caducidad', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=15, null=True)),
                ('nombramiento', models.CharField(choices=[('Titular', 'Titular'), ('Contrato', 'A Contrato')], max_length=15)),
                ('lugar_trabajo', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('estado_civil', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='usuarios.estadocivil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='usuarios.roles')),
            ],
        ),
    ]
