# Generated by Django 5.1.6 on 2025-07-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'PerfilUsuario', 'verbose_name_plural': 'PerfilesUsuarios'},
        ),
        migrations.AlterModelTable(
            name='perfilusuario',
            table='perfilUsuario',
        ),
    ]
